### ISSUE TITLE
it does not work

### ISSUE THREAD

**Issue by lookerjin** [bougou/go-ipmi#1]
![image](https://user-images.githubusercontent.com/48153933/149671195-2091a230-b41e-4425-8e48-63ab75627ac5.png)

**Comment by lookerjin** [comment]
but ipmitool works ok

**Comment by bougou** [comment]
You can enable debug and paste out the result.

```go
  client, err := ipmi.NewClient(host, port, username, password)
  if err != nil {
  panic(err)
  }

  // you can open debug switch
  client.WithDebug(true)
```

If you run `goipmi` cmd, you can use `-d` option for debug.

By the way, how `127.0.0.1` can be used to connect to **Remote BMC IP** ??

**Comment by lookerjin** [comment]
Actually，its a Ipmi-Simulator，check this one **https://github.com/vapor-ware/ipmi-simulator.git**
I was opening port 623 on my pc localhost and use ipmitool to check，its works and get sel back

AND I HAVE A REAL MACHINE, ITS WORKS ON YOU CODE, BUT I DONT KNOW **HOW TO CATCH THIS SDR READING VALUE
, LIKE CPU TEMPERATURE, THANK YOU**
![image](https://user-images.githubusercontent.com/48153933/149723312-ef9dae41-15ee-45d6-815f-1d2c3ea58c7d.png)

**Comment by bougou** [comment]
IPMI SDR record is a little bit complicated to parse, the Sensor Reading value needs some conversion, it's not implemented yet, sorry.

I will comment here when SDR record parsing finished.

**Comment by bougou** [comment]
IPMI SDR record does not contain the "current" reading of sensor. You can get sensor name, sensor number and other attributes of the sensor from the SDR record (`GetSDR`), and get the current reading by `GetSensorReading`.

Now,  just using `GetSensors` method will get you there.

eg:

```go
	sensors, err := client.GetSensors(ipmi.SensorFilterOptionIsThreshold, ipmi.SensorFilterOptionIsReadingValid)
	if err != nil {
		panic(err)
	}

	for _, sensor := range sensors {
		fmt.Printf("%20s | %#02x | %20s | %.3f \n", sensor.Name, sensor.Number, sensor.SensorUnit.String(), sensor.Value)	}
```
