### ISSUE TITLE
rakp1 failed, err: unpack session setup response failed, err: unpacked data is too short

### ISSUE THREAD

**Issue by ZhangHaoNanIT** [bougou/go-ipmi#11]
## I will report an error when I link the bmc using the following method 

```
func (b BmcClient) BmcClient() (clients []*ipmi.Client, err error) {
	clients = make([]*ipmi.Client, 0)
	if len(b.Hosts) == 0 {
		return nil, errors.New("not found host")
	}
	for _, host := range b.Hosts {
		client, err := ipmi.NewClient(host.IP, host.Port, host.Username, host.Password)
		if err != nil {

			return nil, err
		}
		switch b.Protocol {
		case "lan":
			client.Interface = ipmi.InterfaceLan
		case "lanplus":
			client.Interface = ipmi.InterfaceLanplus
		case "open":
			client.Interface = ipmi.InterfaceOpen
		default:
			return nil, fmt.Errorf("not protocol type %s", b.Protocol)
		}
		if err := client.Connect(); err != nil {
			return nil, err
		}
		clients = append(clients, client)
	}
	return clients, nil
}
```

`rakp1 failed, err: unpack session setup response failed, err: unpacked data is too short`

**Comment by bougou** [comment]
You can have a try to use `ipmi.NewClient` function for `lan`/`lanplus` protocol, and use `ipmi.NewOpenClient` function for `open` protocol to create the `ipmi.Client`.

**Comment by ZhangHaoNanIT** [comment]
Thank you very much

**Comment by ZhangHaoNanIT** [comment]
I tried or failed. The tested server is Lenovo ThinkSystem SR650

**Comment by bougou** [comment]
What protocol is used to connect the failed machine?
Does `ipmitool` succeed to connect using the same protocol?

And you can enable debug by setting `client.WithDebug(true)` before `client.Connect`, and paste the log here.

**Comment by ZhangHaoNanIT** [comment]
> client.Connect

**Comment by ZhangHaoNanIT** [comment]
I found the problem. If there is a `client. Connect()` session, this error will be reported. Then I launch a link and the next one will report this error
