### ISSUE TITLE
Concurrent requests will have some timeouts without returning results

### ISSUE THREAD

**Issue by gophernancy** [bougou/go-ipmi#14]
When I use ipmitools command, 50 concurrent requests can return all,
but I use this package 23 concurrent request has one timeout.
The result:
![image](https://user-images.githubusercontent.com/3292071/224936867-42e1dd28-6453-412b-93a2-b33b2ee825c6.png)

![image](https://user-images.githubusercontent.com/3292071/224936720-40518113-e8ff-4db6-8e79-910b471ea20b.png)

The code:

`package main

import (
	"bytes"
	"errors"
	"fmt"
	"github.com/bougou/go-ipmi"
	"os/exec"
	"sync"
	"sync/atomic"
	"time"
)

var total atomic.Int32

func main() {
	var wg sync.WaitGroup
	ip := "xxxxxxx"
	port := 623
	username := "xxxxx"
	password := "xxxxx"
	for i := 0; i < 23; i++ {
		wg.Add(1)
		getResultFromIPMI(ip, port, username, password, &wg)
		//getCmdOut()
	}
	wg.Wait()
}

func getCmdOut() {
	cmd := "./ipmitool -I lanplus -H xxxxxx -U xxxxx -P xxxxxxx  fru"
	cmd2 := exec.Command("sh", "-c", cmd)

	var out bytes.Buffer
	var stderr bytes.Buffer
	cmd2.Stdout = &out
	cmd2.Stderr = &stderr
	err := cmd2.Run()
	if err != nil {
		fmt.Println(errors.New(fmt.Sprint(err) + ": " + stderr.String()))
		return
	}
	fmt.Println(out.String())
	total.Add(1)
	fmt.Println("total:", total)
}

// 走ipmi协议取数据
func getResultFromIPMI(ip string, port int, username, password string, wg *sync.WaitGroup) ([][]interface{}, error) {
	defer wg.Done()
	client, err := connectIPMI(ip, port, username, password) //连接ipmi
	if err != nil {
		return nil, err
	}
	defer client.Close()
	//从ipmi协议取数据
	var arr [][]interface{}
	arr, err = fru(client) //取sensor类型数据
	if err != nil {
		return nil, err
	}
	fmt.Println(arr)
	return arr, nil
}

// 连接ipmi
func connectIPMI(ip string, port int, username string, password string) (*ipmi.Client, error) {
	var c *ipmi.Client
	var err error
	//没有，重新连接
	c, err = ipmi.NewClient(ip, port, username, password)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}
	c.WithInterface("lanplus")
	c.WithTimeout(30 * time.Second)
	if err = c.Connect(); err != nil { //TODO 有时候很慢，有时候很快
		fmt.Println(err)
		return nil, err
	}
	c.Interface = "lanplus"
	//defer c.Close()                  //连接缓存就不用关闭了
	return c, nil
}

// 取fru类型数据
func fru(client *ipmi.Client) ([][]interface{}, error) {
	res, err := client.GetFRUs() //2秒
	if err != nil {
		return nil, err
	}
	arr := make([][]interface{}, len(res), len(res))
	for index, value := range res {
		item := make([]interface{}, 1, 1)
		item[0] = value.String()
		arr[index] = item
	}
	return arr, nil
}
`

**Comment by gophernancy** [comment]
"go run -race  test.go" that also has problem.
![image](https://user-images.githubusercontent.com/3292071/225188055-41686a5e-426a-4bc8-8b1b-afdf8cd4cf92.png)

**Comment by yonwoo9** [comment]
Maybe you should remove the username and password from your code

**Comment by gophernancy** [comment]
> 

Ok, I remove them.
