### ISSUE TITLE
AuthenticationAlgorithm， IntegrityAlgorithm 和 ConfidentialityAlgorithm 这三个参数可以指定么

### ISSUE THREAD

**Issue by mei-rune** [bougou/go-ipmi#16]
两个要求
1. 可以由参数指定么
2. 不指定可以自动选择么, 我记得  GetChannelCipherSuitesCmd  这个可以返回主机支持的参数列表。

**Comment by bougou** [comment]
I added `WithCipherSuiteID(cipherSuiteID CipherSuiteID)` method to the Client, you can use this method to specify custom cipher suite during session request.

Defaults to use `CipherSuiteID3`
