### ISSUE TITLE
ParseSDR failed, err: sdr data must be longer than 5

### ISSUE THREAD

**Issue by bcspragu** [bougou/go-ipmi#17]
Hello there, and thanks again for implementing sensor readings in #15!

I use the sensor readings to monitor my home server temps over IPMI, you can see [the code here](https://github.com/bcspragu/m1000e-prometheus/blob/248300d6a35dcce233a53a9524a8dd169039038a/ipmi/ipmi.go#L60). Most of the time, it works flawlessly, but after running for a while, I occasionally see this behavior:

![image](https://github.com/bougou/go-ipmi/assets/2402010/4f74d103-5892-42f6-bed7-27bed826130e)

Basically, the data looks good, and then it alternates between the failure `ParseSDR failed, err: sdr data must be longer than 5` and returning a value of `-124`. When I manually run:

```
ipmitool -I lanplus -H <ip> -U <user> -P <pass> sensor get 'Ambient Temp'
```

I get the correct output of `Sensor Reading        : 30 (+/- 1) degrees C`

It seems like something is getting out of sync, perhaps with the long-lived connection I'm creating. I saw this behavior once before, maybe after the same amount of time, but I don't have logs for the last time I saw this. This time, the monitoring was running for ~87 hours and 41 minutes before showing the wrong readings.

Any ideas?

**Comment by bougou** [comment]
I finally found that the UDP exchange method should be synchronized for concurrent access. 

The long-lived connection uses a go-routine, keepAliveSession, to periodically exchange 'GetCurrentSessionInfo' request/response to keep the session alive. This background exchange may interfere with the behavior of other commands.

Now starts from [v0.5.11](https://github.com/bougou/go-ipmi/commit/d98697c41502bb804c8fd808e1cad4cd31fb8839), a lock is used by udpclient for concurency protection during the udp exchange (send/recv) procedure.
