### ISSUE TITLE
fruHeader.xxxOffset8B shoule less than fruAreaInfoRes.AreaSizeBytes

### ISSUE THREAD

**Issue by ssskrillexxx** [bougou/go-ipmi#24]

**Comment by ssskrillexxx** [comment]
if fruHeader.ChassisOffset8B != 0 {
    ...
}
should be change to
if fruHeader.ChassisOffset8B != 0 && uint16(fruHeader.ChassisOffset8B) * 8 < fruAreaInfoRes.AreaSizeBytes {
    ...
}

**Comment by bougou** [comment]
@ssskrillexxx Thanks for your reminder. Fix is committed.
