### ISSUE TITLE
当 GetSensorReading 返回错误时，sensor.readingUnavailable 为默认值 false，导致 sensor.IsReadingValid 判断不符合预期

### ISSUE THREAD

**Issue by duanchao2035** [bougou/go-ipmi#27]
https://github.com/bougou/go-ipmi/blob/main/cmd_get_sensors.go#L162
当 GetSensorReading 返回错误时，函数会提前返回。此时 sensor.readingUnavailable 为默认值 false，并且没有从 readingRes 获取到 sensor 的 value。因为没有获取成功数据，预期调用 sensor.ReadingStr 应该返回 N/A，但由于 sensor.readingUnavailable 为默认值 false，导致返回了 0 值。

**Comment by bougou** [comment]
I change the `readingUnavailable` field to `readingAvailable` (defaults to false). It would only be updated by success return of GetSensorReading.
