### ISSUE TITLE
errors for lanprint 

### ISSUE THREAD

**Issue by yehaifeng** [bougou/go-ipmi#28]
When i execute command `ipmi-go lan print 1`, that is a error:
```
error: GetLanConfig failed, err: get lan config param (Destination Addresses) failed, err: the data for param (Destination Addresses) is too short, input (13), required (18)
```

i find the relative code like this.
```
// cmd_get_lan_config_params.go
	case LanParam_AlertDestinationAddress:
		lanConfig.AlertDestinationAddress = AlertDestinationAddress{
			SetSelector:         paramData[0],
			AddressFormat:       (paramData[1] & 0xf0) >> 4,
			IP4UseBackupGateway: isBit0Set(paramData[2]),
			IP4IP:               net.IP(paramData[3:7]),
			IP4MAC:              net.HardwareAddr(paramData[7:12]),
			IP6IP:               net.IP(paramData[2:18]),
		}
```

```
var LanParams = []LanParam{
// types_lan_params.go
        ...
	{Selector: LanParam_AlertDestinationAddress, DataSize: 18, Name: "Destination Addresses"},
        ...
}
```

So why need to check this size.

**Comment by bougou** [comment]
To fetch all lan config information, we need to call `GetLanConfigParams` method many times for each specific lanParam, and interpret the returned paramData ([]byte) accordingly.

Checking the length of paramData is to avoid possible array out-of-bound index access panic.

But there was a bug when handling the length for `LanParam_AlertDestinationAddress`. It holds 13 bytes if AddressFormat is IPv4 and 18 bytes if IPv6. 

It's already fixed at https://github.com/bougou/go-ipmi/commit/bb3ee1713cc8f486a1d1b57ea6039a925850522b. Try new version v0.5.1.
