### ISSUE TITLE
ChassisControlHardwareRest action

### ISSUE THREAD

**Issue by P44elovod** [bougou/go-ipmi#29]
Hey, thx for your lib, it's awesome. 
Looks like [ChassisControlHardwareRest](https://github.com/bougou/go-ipmi/blob/d2c90c2bc8d743b46be4f44f55b17991ed6f097f/cmd_chassis_control.go#L9) is supposed to invoke Hard Reset, but the name is a little bit confusing. 

Could you pls tell me if you are going to change it?

**Comment by bougou** [comment]
Thanks for your reminder.

The `Rest` is clearly a typo. I changed `ChassisControlHardwareRest` to `ChassisControlHardReset` in commit https://github.com/bougou/go-ipmi/commit/904ecc5a8ddd470e81a9a3ac4e9ed9df7975cd78.

Try version v0.5.2.

**Comment by P44elovod** [comment]
thank you)
