### ISSUE TITLE
"No Cipher Suite match with proposed security algorithms" when connecting to Lenovo chassis

### ISSUE THREAD

**Issue by thomaskchan** [bougou/go-ipmi#37]
Seems to work fine on a Supermicro but ran into this issue when connecting to a Lenovo.

client connect failed, err: cmd: RMCP+ Open Session failed, err: rakp status code error: (0x11) No Cipher Suite match with proposed security algorithms

**Comment by thomaskchan** [comment]
I think it requires cipher suite 17 when using ipmitool but not sure yet how to specify this in go-ipmi.

**Comment by thomaskchan** [comment]
If I change bestSuite to CipherSuiteID17, then it does seem to work.  Not sure if there's a better way so that it tries 17 and not just 3?

```diff --git a/types_cipher_suite_id.go b/types_cipher_suite_id.go
index 9bac1fa..83f561f 100644
--- a/types_cipher_suite_id.go
+++ b/types_cipher_suite_id.go
@@ -136,7 +136,7 @@ func findBestCipherSuite() CipherSuiteID {
                // so we should always be able to fall back to that if better
                // options are not available.
                // CipherSuiteID3 -> 01h, 01h, 01h
-               bestSuite = CipherSuiteID3
+               bestSuite = CipherSuiteID17
        }
        return bestSuite
 }
```

**Comment by thomaskchan** [comment]
While changing to 17 works for the lenovo, this then breaks on the supermicro.  So, I think the detection needs to be sorted out?

**Comment by thomaskchan** [comment]
I found the client.WithCipherSuiteID() that I can use.

I do think it would be a good idea to have a detection though where it first tries 17, then 3, unless there's a way to get that information from the host itself?

**Comment by bougou** [comment]
@thomaskchan I added the code of trying different ciphers during Connect if no specific cipher suite is set by `client.WithCipherSuiteID()`.
