### ISSUE TITLE
Add ability to change default session privilege limit before opening session

### ISSUE THREAD

**Issue by akmubi** [bougou/go-ipmi#38]
I've encountered a problem when establishing IPMIv2.0/RMCP+ session with non-admin users. The specification says that the privilege limit of a session (RAKP2, name-only lookup) must be no greater than the privilege limit for the channel/user (also, it can't be greater than the privilege limit of a proposed cipher suite). For example, if we have the following:
```
user_priv_limit = 0x02
chan_priv_limit = 0x04
cipher_suite_priv_limit = 0x04
session_priv_limit = 0x04
```

the effective session privilege limit will be `0x02` (User) and attempting to set a value greater than this value will result in an error (in this case, sending Set Session Privilege command with value `0x04`).

This situation also affects IPMIv1.5 sessions because, according to the specification, BMC should return an error if maximum privilege level is greater than the channel/user limit (Activate Session).

I suggest adding a new function like WithMaxPrivilege that can override the default privilege limit used when opening a new session. This is basically `-L` flag from `ipmitool`.

**Comment by bougou** [comment]
@akmubi  The `WithMaxPrivilegeLevel` method is added. You can try main branch code to see if it resolves your problem. 
I will release a new version later if the code is ok.
