### ISSUE TITLE
why client.GetSensors() is unstable?

### ISSUE THREAD

**Issue by gophernancy** [bougou/go-ipmi#7]
I found two phenomena and need your help. Would you like to help me?
1、every time when I connect, then getSensors is unstable:
Sometimes, I can get the data that I want. 
Sometimes, I can't get data and return an error:

Get Channel Authentication Capabilities failed, err: client udp exchange msg failed, err: read from conn failed, err: read udp 10.128.6.107:50132->10.128.9.201:623: i/o timeout

sometimes, I got another error:

GetSDRs failed, err: ParseSDR failed, err: sdr data must be longer than 5

2、 when I connect one time, use this connect to getSensors more times,  
I can get data in minutes, 
if I don't get data in minutes, then I use before conn to get data, then I got an error:

GetSDR for recordID (0x0) failed, err: client udp exchange msg failed, err: read from conn failed, err: read udp 10.128.6.107:52088->10.128.9.201:623: i/o timeout

I guess connect may be expired? If I guess right, how does set connect never be expired?

**Comment by bougou** [comment]
The problem of "i/o timeout" is due to the timeout of IPMI LAN auth session, I will add the feature of keeping the session active right away, :)

As for the "GetSDRs failed" problem, can you paste more debug info?

**Comment by bougou** [comment]
The i/0 timeout issue is fixed in latest main (v0.3.0).

**Comment by gophernancy** [comment]
> The problem of "i/o timeout" is due to the timeout of IPMI LAN auth session, I will add the feature of keeping the session active right away, :)
> 
> As for the "GetSDRs failed" problem, can you paste more debug info?

"GetSDRs failed", I didn't find the condition for this error. When I get data many times, I found this error only once. If I meet again, I will print more info.

Thank you very much for your answer.

Is 0.3.0 version equal with main version?
