### ISSUE TITLE
Code self selection

### ISSUE THREAD

**Issue by ZhangHaoNanIT** [bougou/go-ipmi#9]
Hi, I'd like to ask you how to set the next time the server starts pxe, and reset the power through the lanplus mode

**Comment by ZhangHaoNanIT** [comment]
client, err := ipmi.NewClient(host, port, username, password)
	// Support local mode client if runs directly on linux
	// client, err := ipmi.NewOpenClient()
	if err != nil {
		panic(err)
	}

	// you can optionally open debug switch
	// client.WithDebug(true)
	client.Interface = "lanplus"
	// Connect will create an authenticated session for you.
	if err := client.Connect(); err != nil {
		panic(err)
	}
	data, err := client.SetSystemBootOptions(&ipmi.SetSystemBootOptionsRequest{
		MarkParameterInvalid: false,
		ParameterSelector:    ipmi.BOPS_BootFlags,
		BootOptionParameter: ipmi.BootOptionParameter{BootFlags: &ipmi.BOP_BootFlags{
			BootDeviceSelector: ipmi.BootDeviceSelectorForcePXE,
			Persist:            false,
			BIOSBootType:       ipmi.BIOSBootTypeLegacy,
			LockoutPowerOff:    false,
		},
		},
	})
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(data.Format())

**Comment by bougou** [comment]
You can use `ChassisControl` command to reset power, like

```go
	if _, err := client.ChassisControl(ipmi.ChassisControlHardwareRest); err != nil {
		fmt.Printf("ChassisControl failed, err: %s", err)
		return
	}
```

And you can try `SetBootDevice` command (added v0.3.0) to set boot device for next boot, which is just a wrapper of `SetSystemBootOptions`.
